# Gerar tabela ASCII completa em UTF-8

lista = []

for i in range(128):
    char = chr(i)
    utf8 = char.encode("utf-8").hex()
    
    dict = {"Caractere": char, "UTF-8": utf8}
    lista.append(dict)
for dit in lista: 
    print(f"{dit},")
    


lista = [
{"Caractere": " ", "UTF-8": "20"},
{"Caractere": "!", "UTF-8": "21"},
{"Caractere": " ' ", "UTF-8": "22"},
{"Caractere": "#", "UTF-8": "23"},
{"Caractere": "$", "UTF-8": "24"},
{"Caractere": "%", "UTF-8": "25"},
{"Caractere": "&", "UTF-8": "26"},
{"Caractere": " ", "UTF-8": "27"},
{"Caractere": "(", "UTF-8": "28"},
{"Caractere": ")", "UTF-8": "29"},
{"Caractere": "*", "UTF-8": "2a"},
{"Caractere": "+", "UTF-8": "2b"},
{"Caractere": ",", "UTF-8": "2c"},
{"Caractere": "-", "UTF-8": "2d"},
{"Caractere": ".", "UTF-8": "2e"},
{"Caractere": "/", "UTF-8": "2f"},
{"Caractere": "0", "UTF-8": "30"},
{"Caractere": "1", "UTF-8": "31"},
{"Caractere": "2", "UTF-8": "32"},
{"Caractere": "3", "UTF-8": "33"},
{"Caractere": "4", "UTF-8": "34"},
{"Caractere": "5", "UTF-8": "35"},
{"Caractere": "6", "UTF-8": "36"},
{"Caractere": "7", "UTF-8": "37"},
{"Caractere": "8", "UTF-8": "38"},
{"Caractere": "9", "UTF-8": "39"},
{"Caractere": ":", "UTF-8": "3a"},
{"Caractere": ";", "UTF-8": "3b"},
{"Caractere": "<", "UTF-8": "3c"},
{"Caractere": "=", "UTF-8": "3d"},
{"Caractere": ">", "UTF-8": "3e"},
{"Caractere": "?", "UTF-8": "3f"},
{"Caractere": "@", "UTF-8": "40"},
{"Caractere": "A", "UTF-8": "41"},
{"Caractere": "B", "UTF-8": "42"},
{"Caractere": "C", "UTF-8": "43"},
{"Caractere": "D", "UTF-8": "44"},
{"Caractere": "E", "UTF-8": "45"},
{"Caractere": "F", "UTF-8": "46"},
{"Caractere": "G", "UTF-8": "47"},
{"Caractere": "H", "UTF-8": "48"},
{"Caractere": "I", "UTF-8": "49"},
{"Caractere": "J", "UTF-8": "4a"},
{"Caractere": "K", "UTF-8": "4b"},
{"Caractere": "L", "UTF-8": "4c"},
{"Caractere": "M", "UTF-8": "4d"},
{"Caractere": "N", "UTF-8": "4e"},
{"Caractere": "O", "UTF-8": "4f"},
{"Caractere": "P", "UTF-8": "50"},
{"Caractere": "Q", "UTF-8": "51"},
{"Caractere": "R", "UTF-8": "52"},
{"Caractere": "S", "UTF-8": "53"},
{"Caractere": "T", "UTF-8": "54"},
{"Caractere": "U", "UTF-8": "55"},
{"Caractere": "V", "UTF-8": "56"},
{"Caractere": "W", "UTF-8": "57"},
{"Caractere": "X", "UTF-8": "58"},
{"Caractere": "Y", "UTF-8": "59"},
{"Caractere": "Z", "UTF-8": "5a"},
{"Caractere": "[", "UTF-8": "5b"},
{"Caractere": "\\", "UTF-8": "5c"},
{"Caractere": "]", "UTF-8": "5d"},
{"Caractere": "^", "UTF-8": "5e"},
{"Caractere": "_", "UTF-8": "5f"},
{"Caractere": "`", "UTF-8": "60"},
{"Caractere": "a", "UTF-8": "61"},
{"Caractere": "b", "UTF-8": "62"},
{"Caractere": "c", "UTF-8": "63"},
{"Caractere": "d", "UTF-8": "64"},
{"Caractere": "e", "UTF-8": "65"},
{"Caractere": "f", "UTF-8": "66"},
{"Caractere": "g", "UTF-8": "67"},
{"Caractere": "h", "UTF-8": "68"},
{"Caractere": "i", "UTF-8": "69"},
{"Caractere": "j", "UTF-8": "6a"},
{"Caractere": "k", "UTF-8": "6b"},
{"Caractere": "l", "UTF-8": "6c"},
{"Caractere": "m", "UTF-8": "6d"},
{"Caractere": "n", "UTF-8": "6e"},
{"Caractere": "o", "UTF-8": "6f"},
{"Caractere": "p", "UTF-8": "70"},
{"Caractere": "q", "UTF-8": "71"},
{"Caractere": "r", "UTF-8": "72"},
{"Caractere": "s", "UTF-8": "73"},
{"Caractere": "t", "UTF-8": "74"},
{"Caractere": "u", "UTF-8": "75"},
{"Caractere": "v", "UTF-8": "76"},
{"Caractere": "w", "UTF-8": "77"},
{"Caractere": "x", "UTF-8": "78"},
{"Caractere": "y", "UTF-8": "79"},
{"Caractere": "z", "UTF-8": "7a"},
{"Caractere": "{", "UTF-8": "7b"},
{"Caractere": "|", "UTF-8": "7c"},
{"Caractere": "}", "UTF-8": "7d"},
{"Caractere": "~", "UTF-8": "7e"}
]